server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
    database: MYSQL
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace

