spring:
  config:
    activate:
      on-profile: knifer-dev
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 5000ms
    connect-timeout: 5000ms
server:
  port: 8081
torch:
  gateway:
    init:
      routes-json-path: test-data/route-groups.json
    loadbalance:
      loadbalancer-class: xit.gateway.core.loadbalancer.impl.RoundRobinLoadbalancer
    route-limiting:
      time-unit: second
      permits-per-unit: 2
      limit: 10