spring:
  config:
    activate:
      on-profile: knifer-dev
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 5000ms
    connect-timeout: 5000ms
  r2dbc:
    username: admin
    password: 123
    url: r2dbcs:mysql://192.168.231.132:6670/torch_game_gateway?SSL=false&sslMode=DISABLED
server:
  port: 8082
torch:
  gateway:
    deacon:
      fuse:
        fuse-class: xit.gateway.deacon.fuse.impl.DefaultFuse
      cluster:
        heart-beat-idle-timeout: 10
        heart-beat-server-port: 9099