spring:
  config:
    activate:
      on-profile: knifer-dev
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 5000ms
    connect-timeout: 5000ms
server:
  port: 8082
torch:
  gateway:
    deacon:
      fuse:
        fuse-class: xit.gateway.core.fuse.impl.DefaultFuse